/** @format */
export const resList = [
  {
    cuisine: "Pizza",
    resName: "Domino's",
    img: "pizza/pizza5.jpg",
    rating: "4.9 Stars",
    deliveryTime: " 34 min min",
  },
  {
    cuisine: "Biryani",
    res: "McDonald's",
    img: "biryani/biryani67.jpg",
    rating: "4.8 Stars",
    deliveryTime: "13 min",
  },
  {
    cuisine: "Butter-chicken",
    res: "Sushi House",
    img: "butter-chicken/butter-chicken6.jpg",
    rating: "1.3 Stars",
    deliveryTime: " 34 min",
  },
  {
    cuisine: "Burger",
    res: "Subway House",
    img: "burger/burger57.jpg",
    rating: "4.4 Stars",
    deliveryTime: " 34 min",
  },
  {
    cuisine: "Rice",
    res: "Olive Garden",
    img: "rice/rice8.jpg",
    rating: "5 Stars",
    deliveryTime: " 34 min",
  },
  {
    cuisine: "Samosa",
    res: "Taco Bell",
    img: "samosa/samosa10.jpg",
    rating: "1.5 Stars",
    deliveryTime: " 34 min",
  },
  {
    cuisine: "Pasta",
    res: "Sweet Green",
    img: "pasta/pasta3.jpg",
    rating: "2.7 Stars",
    deliveryTime: " 34 min",
  },
  {
    cuisine: "Dosa",
    res: "Outback Steakhouse",
    img: "dosa/dosa83.jpg",
    rating: "4.0 Stars",
    deliveryTime: " 34 min",
  },
  {
    cuisine: "Desert",
    res: "Hungry lion",
    img: "dessert/dessert26.jpg",
    rating: "4.9 Stars",
    deliveryTime: " 34 min",
  },
  {
    cuisine: "Idly",
    res: "Subway",
    img: "idly/idly20.jpg",
    rating: "4.6 Stars",
    deliveryTime: " 34 min",
  },
  {
    cuisine: "Pizza",
    res: "Domino's",
    img: "pizza/pizza10.jpg",
    rating: "3.5 Stars",
    deliveryTime: " 34 min",
  },
  {
    cuisine: "Biryani",
    res: "McDonald's",
    img: "biryani/biryani63.jpg",
    rating: "2.5 Stars",
    deliveryTime: " 34 min",
  },
  {
    cuisine: "Butter-chicken",
    res: "Sushi House",
    img: "butter-chicken/butter-chicken9.jpg",
    rating: "3.0 Stars",
    deliveryTime: " 34 min",
  },
  {
    cuisine: "Burger",
    res: "Subway House",
    img: "burger/burger5.jpg",
    rating: "4.2 Stars",
    deliveryTime: " 34 min",
  },
  {
    cuisine: "Rice",
    res: "Olive Garden",
    img: "rice/rice13.jpg",
    rating: "3.5 Stars",
    deliveryTime: " 34 min",
  },
];
